[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EnergySystemModels-en"
authors = [{name = "Zoheir HADID", email = "zoheir.hadid@example.com"}]
dynamic = ["version", "description"]
